/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JFrame;

/**
 *
 * @author leandrocnb
 */
public class Desktop extends javax.swing.JFrame {

    /**
     * Creates new form Desktop
     */
    public Desktop() {
        initComponents();
        Inicial.setVisible(true);
        Cadastrar_Funcionarios.setVisible(false);
        Visualizar_Funcionarios.setVisible(false);
        Cadastrar_Produtos.setVisible(false);
        Visualizar_Estoque.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaInicial = new javax.swing.JPanel();
        modo_adm = new javax.swing.JLabel();
        cadastrar_funcionario = new javax.swing.JLabel();
        base_cadFuncionario1 = new javax.swing.JLabel();
        visualizar_funcionarios = new javax.swing.JLabel();
        base_cadFuncionario2 = new javax.swing.JLabel();
        cadastrar_produto = new javax.swing.JLabel();
        base_cadFuncionario3 = new javax.swing.JLabel();
        visualizar_estoque = new javax.swing.JLabel();
        base_cadFuncionario4 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        Inicial = new javax.swing.JPanel();
        Frase_Boas_Vindas = new javax.swing.JLabel();
        Cadastrar_Funcionarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fundo_cadastrar_funcionario = new javax.swing.JLabel();
        Visualizar_Funcionarios = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fundo_visualizar_funcionario = new javax.swing.JLabel();
        Cadastrar_Produtos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fundo_cadastrar_produto = new javax.swing.JLabel();
        Visualizar_Estoque = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fundo_visualizar_estoque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        TelaInicial.setBackground(new java.awt.Color(193, 171, 254));
        TelaInicial.setLayout(null);

        modo_adm.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        modo_adm.setForeground(new java.awt.Color(255, 255, 255));
        modo_adm.setText("MODO ADM");
        TelaInicial.add(modo_adm);
        modo_adm.setBounds(40, 20, 199, 47);

        cadastrar_funcionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrar_funcionario.setText("Cadastrar Funcionário");
        cadastrar_funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrar_funcionarioMouseClicked(evt);
            }
        });
        TelaInicial.add(cadastrar_funcionario);
        cadastrar_funcionario.setBounds(90, 70, 190, 50);

        base_cadFuncionario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/base_button170x40.png"))); // NOI18N
        TelaInicial.add(base_cadFuncionario1);
        base_cadFuncionario1.setBounds(100, 70, 180, 50);

        visualizar_funcionarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visualizar_funcionarios.setText("Visializar Funcionários");
        visualizar_funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualizar_funcionariosMouseClicked(evt);
            }
        });
        TelaInicial.add(visualizar_funcionarios);
        visualizar_funcionarios.setBounds(80, 130, 210, 50);

        base_cadFuncionario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/base_button170x40.png"))); // NOI18N
        TelaInicial.add(base_cadFuncionario2);
        base_cadFuncionario2.setBounds(100, 130, 180, 50);

        cadastrar_produto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrar_produto.setText("Cadastrar Produto");
        cadastrar_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrar_produtoMouseClicked(evt);
            }
        });
        TelaInicial.add(cadastrar_produto);
        cadastrar_produto.setBounds(90, 190, 190, 50);

        base_cadFuncionario3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/base_button170x40.png"))); // NOI18N
        TelaInicial.add(base_cadFuncionario3);
        base_cadFuncionario3.setBounds(100, 190, 180, 50);

        visualizar_estoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visualizar_estoque.setText("Visualizar Estoque");
        visualizar_estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualizar_estoqueMouseClicked(evt);
            }
        });
        TelaInicial.add(visualizar_estoque);
        visualizar_estoque.setBounds(90, 250, 200, 50);

        base_cadFuncionario4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/base_button170x40.png"))); // NOI18N
        TelaInicial.add(base_cadFuncionario4);
        base_cadFuncionario4.setBounds(100, 250, 180, 50);

        Inicial.setBackground(new java.awt.Color(193, 171, 254));
        Inicial.setPreferredSize(new java.awt.Dimension(1053, 566));

        Frase_Boas_Vindas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Frase_Boas_Vindas.setForeground(new java.awt.Color(255, 255, 255));
        Frase_Boas_Vindas.setText("Bem Vindo ao Sistema de Pagamento Por Crachá");

        javax.swing.GroupLayout InicialLayout = new javax.swing.GroupLayout(Inicial);
        Inicial.setLayout(InicialLayout);
        InicialLayout.setHorizontalGroup(
            InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicialLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(Frase_Boas_Vindas)
                .addGap(104, 104, 104))
        );
        InicialLayout.setVerticalGroup(
            InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicialLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(Frase_Boas_Vindas)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        Cadastrar_Funcionarios.setBackground(new java.awt.Color(193, 171, 254));
        Cadastrar_Funcionarios.setPreferredSize(new java.awt.Dimension(1053, 566));
        Cadastrar_Funcionarios.setLayout(null);

        jLabel1.setText("Aqui é a tela Cadastrar Funcionario");
        Cadastrar_Funcionarios.add(jLabel1);
        jLabel1.setBounds(30, 30, 250, 14);

        fundo_cadastrar_funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundo1009x600.png"))); // NOI18N
        Cadastrar_Funcionarios.add(fundo_cadastrar_funcionario);
        fundo_cadastrar_funcionario.setBounds(0, 0, 1010, 601);

        Visualizar_Funcionarios.setBackground(new java.awt.Color(193, 171, 254));
        Visualizar_Funcionarios.setPreferredSize(new java.awt.Dimension(1053, 566));
        Visualizar_Funcionarios.setLayout(null);

        jLabel2.setText("Aqui é a tela Visualizar funcionário");
        Visualizar_Funcionarios.add(jLabel2);
        jLabel2.setBounds(40, 30, 240, 14);

        fundo_visualizar_funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundo1009x600.png"))); // NOI18N
        Visualizar_Funcionarios.add(fundo_visualizar_funcionario);
        fundo_visualizar_funcionario.setBounds(0, 0, 1009, 601);

        Cadastrar_Produtos.setBackground(new java.awt.Color(193, 171, 254));
        Cadastrar_Produtos.setPreferredSize(new java.awt.Dimension(1053, 566));
        Cadastrar_Produtos.setLayout(null);

        jLabel3.setText("Aqui é a tela Cadastrar Produto");
        Cadastrar_Produtos.add(jLabel3);
        jLabel3.setBounds(30, 30, 260, 14);

        fundo_cadastrar_produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundo1009x600.png"))); // NOI18N
        Cadastrar_Produtos.add(fundo_cadastrar_produto);
        fundo_cadastrar_produto.setBounds(0, 0, 1009, 601);

        Visualizar_Estoque.setBackground(new java.awt.Color(193, 171, 254));
        Visualizar_Estoque.setPreferredSize(new java.awt.Dimension(1053, 566));
        Visualizar_Estoque.setLayout(null);

        jLabel4.setText("Aqui é a tela Visualizar Estoque");
        Visualizar_Estoque.add(jLabel4);
        jLabel4.setBounds(30, 30, 240, 14);

        fundo_visualizar_estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundo1009x600.png"))); // NOI18N
        Visualizar_Estoque.add(fundo_visualizar_estoque);
        fundo_visualizar_estoque.setBounds(0, 0, 1009, 601);

        jLayeredPane2.setLayer(Inicial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Cadastrar_Funcionarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Visualizar_Funcionarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Cadastrar_Produtos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Visualizar_Estoque, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cadastrar_Funcionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Inicial, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Visualizar_Funcionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Cadastrar_Produtos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Visualizar_Estoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(Cadastrar_Funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Inicial, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Visualizar_Funcionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Cadastrar_Produtos, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Visualizar_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
        );

        TelaInicial.add(jLayeredPane2);
        jLayeredPane2.setBounds(340, 30, 1010, 660);

        getContentPane().add(TelaInicial, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_funcionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrar_funcionarioMouseClicked
        Inicial.setVisible(false);
        Cadastrar_Funcionarios.setVisible(true);
        Visualizar_Funcionarios.setVisible(false);
        Cadastrar_Produtos.setVisible(false);
        Visualizar_Estoque.setVisible(false);
    }//GEN-LAST:event_cadastrar_funcionarioMouseClicked

    private void visualizar_funcionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizar_funcionariosMouseClicked
        Inicial.setVisible(false);
        Cadastrar_Funcionarios.setVisible(false);
        Visualizar_Funcionarios.setVisible(true);
        Cadastrar_Produtos.setVisible(false);
        Visualizar_Estoque.setVisible(false);
    }//GEN-LAST:event_visualizar_funcionariosMouseClicked

    private void cadastrar_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrar_produtoMouseClicked
        Inicial.setVisible(false);
        Cadastrar_Funcionarios.setVisible(false);
        Visualizar_Funcionarios.setVisible(false);
        Cadastrar_Produtos.setVisible(true);
        Visualizar_Estoque.setVisible(false);
    }//GEN-LAST:event_cadastrar_produtoMouseClicked

    private void visualizar_estoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizar_estoqueMouseClicked
        Inicial.setVisible(false);
        Cadastrar_Funcionarios.setVisible(false);
        Visualizar_Funcionarios.setVisible(false);
        Cadastrar_Produtos.setVisible(false);
        Visualizar_Estoque.setVisible(true);
    }//GEN-LAST:event_visualizar_estoqueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrame desk = new Desktop();
            desk.setVisible(true);
            desk.setResizable(true);
            desk.setExtendedState(MAXIMIZED_BOTH);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cadastrar_Funcionarios;
    private javax.swing.JPanel Cadastrar_Produtos;
    private javax.swing.JLabel Frase_Boas_Vindas;
    private javax.swing.JPanel Inicial;
    private javax.swing.JPanel TelaInicial;
    private javax.swing.JPanel Visualizar_Estoque;
    private javax.swing.JPanel Visualizar_Funcionarios;
    private javax.swing.JLabel base_cadFuncionario1;
    private javax.swing.JLabel base_cadFuncionario2;
    private javax.swing.JLabel base_cadFuncionario3;
    private javax.swing.JLabel base_cadFuncionario4;
    private javax.swing.JLabel cadastrar_funcionario;
    private javax.swing.JLabel cadastrar_produto;
    private javax.swing.JLabel fundo_cadastrar_funcionario;
    private javax.swing.JLabel fundo_cadastrar_produto;
    private javax.swing.JLabel fundo_visualizar_estoque;
    private javax.swing.JLabel fundo_visualizar_funcionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel modo_adm;
    private javax.swing.JLabel visualizar_estoque;
    private javax.swing.JLabel visualizar_funcionarios;
    // End of variables declaration//GEN-END:variables
}
