/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author leandrocnb
 */
public class Desktop extends javax.swing.JFrame {

    /**
     * Creates new form Desktop
     */
    public Desktop() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelInicio = new javax.swing.JPanel();
        btcadFuncIni = new javax.swing.JLabel();
        btvisFuncIni = new javax.swing.JLabel();
        btcadProdIni = new javax.swing.JLabel();
        btvisProdIni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelcadFuncionario = new javax.swing.JPanel();
        btcadFuncCadFunc = new javax.swing.JLabel();
        btvisFuncCadFunc = new javax.swing.JLabel();
        btcadProdCadFunc = new javax.swing.JLabel();
        btvisProdCadFunc = new javax.swing.JLabel();
        estadoCadFunc = new javax.swing.JComboBox<>();
        cargoCadFunc = new javax.swing.JComboBox<>();
        nomeCompletoCadFunc = new javax.swing.JTextField();
        carteiraDeTrabCadFunc = new javax.swing.JTextField();
        TituloDeEleitorCadFunc = new javax.swing.JTextField();
        pisCadFunc = new javax.swing.JTextField();
        cepCadFunc = new javax.swing.JTextField();
        numeroCadFunc = new javax.swing.JTextField();
        cidadeCadFunc = new javax.swing.JTextField();
        logradouroCadFunc = new javax.swing.JTextField();
        complementoCadFunc = new javax.swing.JTextField();
        bairroCadFunc = new javax.swing.JTextField();
        btcancelarCadFunc = new javax.swing.JLabel();
        btcadastrarCadFunc = new javax.swing.JLabel();
        dataNascCadFunc = new javax.swing.JFormattedTextField();
        rgCadFunc = new javax.swing.JFormattedTextField();
        cpfCadFunc = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanelvisFuncionario = new javax.swing.JPanel();
        btcadFuncVisFunc = new javax.swing.JLabel();
        btcadProdVisFunc = new javax.swing.JLabel();
        btvisProdVisFunc = new javax.swing.JLabel();
        btatualizarVisFunc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelcadProduto = new javax.swing.JPanel();
        btcadFuncCadProd = new javax.swing.JLabel();
        btvisFuncCadProd = new javax.swing.JLabel();
        btvisProdCadProd = new javax.swing.JLabel();
        nomeProdutoCadProd = new javax.swing.JTextField();
        qunatidadeCadProd = new javax.swing.JTextField();
        precoCadProd = new javax.swing.JTextField();
        btcancelarCadProd = new javax.swing.JLabel();
        descricaoCadProd = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanelvisProduto = new javax.swing.JPanel();
        btcadFuncVisProd = new javax.swing.JLabel();
        btvisFuncVisProd = new javax.swing.JLabel();
        btcadProdVisProd = new javax.swing.JLabel();
        btatualizarAtuProd = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelatuFuncionario = new javax.swing.JPanel();
        btcadFuncAtuFunc = new javax.swing.JLabel();
        btvisFuncAtuFunc = new javax.swing.JLabel();
        btcadProdAtuFunc = new javax.swing.JLabel();
        btvisProdAtuFunc = new javax.swing.JLabel();
        nomeCompletoAtuFunc = new javax.swing.JTextField();
        carteiraDeTrabAtuFunc = new javax.swing.JTextField();
        tituloDeEleitorAtuFunc = new javax.swing.JTextField();
        pisAtuFunc = new javax.swing.JTextField();
        cepAtuFunc = new javax.swing.JTextField();
        numeroAtuFunc = new javax.swing.JTextField();
        cidadeAtuFunc = new javax.swing.JTextField();
        logradouroAtuFunc = new javax.swing.JTextField();
        complementoAtuFunc = new javax.swing.JTextField();
        bairroAtuFunc = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        btcancelarAtuFunc = new javax.swing.JLabel();
        rgAtuFunc = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelatuProduto = new javax.swing.JPanel();
        btcadFuncAtuProd = new javax.swing.JLabel();
        btvisFuncAtuProd = new javax.swing.JLabel();
        btvisProdAtuProd = new javax.swing.JLabel();
        btcadProdAtuProd = new javax.swing.JLabel();
        nomeProdAtuProd = new javax.swing.JTextField();
        quantidadeAtuProd = new javax.swing.JTextField();
        precoAtuProd = new javax.swing.JTextField();
        descricaoAtuProd = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btcancelarAtuProd = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 626));
        setMinimumSize(new java.awt.Dimension(1024, 626));
        setPreferredSize(new java.awt.Dimension(1024, 626));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 576));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanelInicio.setMaximumSize(new java.awt.Dimension(1024, 576));
        jPanelInicio.setMinimumSize(new java.awt.Dimension(1024, 576));
        jPanelInicio.setLayout(null);

        btcadFuncIni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadFuncIniMouseClicked(evt);
            }
        });
        jPanelInicio.add(btcadFuncIni);
        btcadFuncIni.setBounds(14, 154, 430, 70);

        btvisFuncIni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisFuncIniMouseClicked(evt);
            }
        });
        jPanelInicio.add(btvisFuncIni);
        btvisFuncIni.setBounds(14, 254, 430, 60);

        btcadProdIni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadProdIniMouseClicked(evt);
            }
        });
        jPanelInicio.add(btcadProdIni);
        btcadProdIni.setBounds(20, 354, 420, 60);

        btvisProdIni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisProdIniMouseClicked(evt);
            }
        });
        jPanelInicio.add(btvisProdIni);
        btvisProdIni.setBounds(20, 454, 420, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Início3.png"))); // NOI18N
        jPanelInicio.add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 576);

        jPanel1.add(jPanelInicio, "Inicio");

        jPanelcadFuncionario.setMaximumSize(new java.awt.Dimension(1024, 576));
        jPanelcadFuncionario.setMinimumSize(new java.awt.Dimension(1024, 576));
        jPanelcadFuncionario.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanelcadFuncionario.setLayout(null);

        btcadFuncCadFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadFuncCadFuncMouseClicked(evt);
            }
        });
        jPanelcadFuncionario.add(btcadFuncCadFunc);
        btcadFuncCadFunc.setBounds(14, 154, 430, 70);

        btvisFuncCadFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisFuncCadFuncMouseClicked(evt);
            }
        });
        jPanelcadFuncionario.add(btvisFuncCadFunc);
        btvisFuncCadFunc.setBounds(14, 254, 430, 60);

        btcadProdCadFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadProdCadFuncMouseClicked(evt);
            }
        });
        jPanelcadFuncionario.add(btcadProdCadFunc);
        btcadProdCadFunc.setBounds(20, 354, 420, 60);

        btvisProdCadFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisProdCadFuncMouseClicked(evt);
            }
        });
        jPanelcadFuncionario.add(btvisProdCadFunc);
        btvisProdCadFunc.setBounds(20, 454, 430, 60);

        estadoCadFunc.setBackground(new java.awt.Color(255, 60, 60));
        estadoCadFunc.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        estadoCadFunc.setForeground(new java.awt.Color(255, 60, 60));
        estadoCadFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        estadoCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCadFuncActionPerformed(evt);
            }
        });
        jPanelcadFuncionario.add(estadoCadFunc);
        estadoCadFunc.setBounds(500, 510, 210, 30);

        cargoCadFunc.setBackground(new java.awt.Color(255, 60, 60));
        cargoCadFunc.setForeground(new java.awt.Color(255, 60, 60));
        cargoCadFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelcadFuncionario.add(cargoCadFunc);
        cargoCadFunc.setBounds(860, 130, 120, 30);

        nomeCompletoCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        nomeCompletoCadFunc.setBorder(null);
        nomeCompletoCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCompletoCadFuncActionPerformed(evt);
            }
        });
        jPanelcadFuncionario.add(nomeCompletoCadFunc);
        nomeCompletoCadFunc.setBounds(520, 140, 330, 20);

        carteiraDeTrabCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        carteiraDeTrabCadFunc.setBorder(null);
        jPanelcadFuncionario.add(carteiraDeTrabCadFunc);
        carteiraDeTrabCadFunc.setBounds(520, 280, 180, 14);

        TituloDeEleitorCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        TituloDeEleitorCadFunc.setBorder(null);
        jPanelcadFuncionario.add(TituloDeEleitorCadFunc);
        TituloDeEleitorCadFunc.setBounds(790, 230, 180, 14);

        pisCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        pisCadFunc.setBorder(null);
        jPanelcadFuncionario.add(pisCadFunc);
        pisCadFunc.setBounds(790, 280, 180, 14);

        cepCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        cepCadFunc.setBorder(null);
        jPanelcadFuncionario.add(cepCadFunc);
        cepCadFunc.setBounds(520, 370, 180, 20);

        numeroCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        numeroCadFunc.setBorder(null);
        jPanelcadFuncionario.add(numeroCadFunc);
        numeroCadFunc.setBounds(520, 420, 180, 20);

        cidadeCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        cidadeCadFunc.setBorder(null);
        jPanelcadFuncionario.add(cidadeCadFunc);
        cidadeCadFunc.setBounds(520, 470, 180, 20);

        logradouroCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        logradouroCadFunc.setBorder(null);
        jPanelcadFuncionario.add(logradouroCadFunc);
        logradouroCadFunc.setBounds(790, 370, 180, 20);

        complementoCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        complementoCadFunc.setBorder(null);
        jPanelcadFuncionario.add(complementoCadFunc);
        complementoCadFunc.setBounds(790, 420, 180, 14);

        bairroCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        bairroCadFunc.setBorder(null);
        jPanelcadFuncionario.add(bairroCadFunc);
        bairroCadFunc.setBounds(790, 470, 180, 14);

        btcancelarCadFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcancelarCadFuncMouseClicked(evt);
            }
        });
        jPanelcadFuncionario.add(btcancelarCadFunc);
        btcancelarCadFunc.setBounds(780, 520, 90, 40);
        jPanelcadFuncionario.add(btcadastrarCadFunc);
        btcadastrarCadFunc.setBounds(900, 520, 90, 40);

        dataNascCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        dataNascCadFunc.setBorder(null);
        try {
            dataNascCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelcadFuncionario.add(dataNascCadFunc);
        dataNascCadFunc.setBounds(520, 230, 180, 14);

        rgCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        rgCadFunc.setBorder(null);
        try {
            rgCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rgCadFunc.setToolTipText("");
        rgCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgCadFuncActionPerformed(evt);
            }
        });
        jPanelcadFuncionario.add(rgCadFunc);
        rgCadFunc.setBounds(520, 180, 180, 14);

        cpfCadFunc.setBackground(new java.awt.Color(255, 232, 232));
        cpfCadFunc.setBorder(null);
        try {
            cpfCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfCadFunc.setToolTipText("");
        cpfCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfCadFuncActionPerformed(evt);
            }
        });
        jPanelcadFuncionario.add(cpfCadFunc);
        cpfCadFunc.setBounds(790, 180, 130, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cadastrar Funcionário3.png"))); // NOI18N
        jPanelcadFuncionario.add(jLabel2);
        jLabel2.setBounds(0, 0, 1024, 576);

        jPanel1.add(jPanelcadFuncionario, "cadFuncionario");

        jPanelvisFuncionario.setMaximumSize(new java.awt.Dimension(1024, 576));
        jPanelvisFuncionario.setMinimumSize(new java.awt.Dimension(1024, 576));
        jPanelvisFuncionario.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanelvisFuncionario.setLayout(null);

        btcadFuncVisFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadFuncVisFuncMouseClicked(evt);
            }
        });
        jPanelvisFuncionario.add(btcadFuncVisFunc);
        btcadFuncVisFunc.setBounds(14, 154, 430, 70);

        btcadProdVisFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadProdVisFuncMouseClicked(evt);
            }
        });
        jPanelvisFuncionario.add(btcadProdVisFunc);
        btcadProdVisFunc.setBounds(14, 354, 430, 60);

        btvisProdVisFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisProdVisFuncMouseClicked(evt);
            }
        });
        jPanelvisFuncionario.add(btvisProdVisFunc);
        btvisProdVisFunc.setBounds(20, 454, 420, 60);

        btatualizarVisFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btatualizarVisFuncMouseClicked(evt);
            }
        });
        jPanelvisFuncionario.add(btatualizarVisFunc);
        btatualizarVisFunc.setBounds(894, 514, 100, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Visualizar Funcionário.png"))); // NOI18N
        jPanelvisFuncionario.add(jLabel3);
        jLabel3.setBounds(0, 0, 1024, 576);

        jPanel1.add(jPanelvisFuncionario, "visFuncionario");

        jPanelcadProduto.setMaximumSize(new java.awt.Dimension(1024, 576));
        jPanelcadProduto.setMinimumSize(new java.awt.Dimension(1024, 576));
        jPanelcadProduto.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanelcadProduto.setLayout(null);

        btcadFuncCadProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadFuncCadProdMouseClicked(evt);
            }
        });
        jPanelcadProduto.add(btcadFuncCadProd);
        btcadFuncCadProd.setBounds(20, 150, 420, 70);

        btvisFuncCadProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisFuncCadProdMouseClicked(evt);
            }
        });
        jPanelcadProduto.add(btvisFuncCadProd);
        btvisFuncCadProd.setBounds(14, 254, 420, 60);

        btvisProdCadProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisProdCadProdMouseClicked(evt);
            }
        });
        jPanelcadProduto.add(btvisProdCadProd);
        btvisProdCadProd.setBounds(20, 450, 420, 60);

        nomeProdutoCadProd.setBackground(new java.awt.Color(255, 232, 232));
        nomeProdutoCadProd.setBorder(null);
        jPanelcadProduto.add(nomeProdutoCadProd);
        nomeProdutoCadProd.setBounds(520, 140, 450, 14);

        qunatidadeCadProd.setBackground(new java.awt.Color(255, 232, 232));
        qunatidadeCadProd.setBorder(null);
        jPanelcadProduto.add(qunatidadeCadProd);
        qunatidadeCadProd.setBounds(520, 200, 180, 14);

        precoCadProd.setBackground(new java.awt.Color(255, 232, 232));
        precoCadProd.setBorder(null);
        jPanelcadProduto.add(precoCadProd);
        precoCadProd.setBounds(790, 200, 180, 14);

        btcancelarCadProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcancelarCadProdMouseClicked(evt);
            }
        });
        jPanelcadProduto.add(btcancelarCadProd);
        btcancelarCadProd.setBounds(780, 520, 90, 40);

        descricaoCadProd.setBackground(new java.awt.Color(255, 232, 232));
        descricaoCadProd.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(255, 232, 232));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        descricaoCadProd.setViewportView(jTextArea1);

        jPanelcadProduto.add(descricaoCadProd);
        descricaoCadProd.setBounds(520, 270, 450, 150);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cadastrar Produto 3.png"))); // NOI18N
        jPanelcadProduto.add(jLabel4);
        jLabel4.setBounds(0, 0, 1024, 576);

        jPanel1.add(jPanelcadProduto, "cadProduto");

        jPanelvisProduto.setMaximumSize(new java.awt.Dimension(1024, 576));
        jPanelvisProduto.setMinimumSize(new java.awt.Dimension(1024, 576));
        jPanelvisProduto.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanelvisProduto.setLayout(null);

        btcadFuncVisProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadFuncVisProdMouseClicked(evt);
            }
        });
        jPanelvisProduto.add(btcadFuncVisProd);
        btcadFuncVisProd.setBounds(20, 150, 420, 70);

        btvisFuncVisProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisFuncVisProdMouseClicked(evt);
            }
        });
        jPanelvisProduto.add(btvisFuncVisProd);
        btvisFuncVisProd.setBounds(24, 254, 410, 60);

        btcadProdVisProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadProdVisProdMouseClicked(evt);
            }
        });
        jPanelvisProduto.add(btcadProdVisProd);
        btcadProdVisProd.setBounds(20, 354, 420, 60);

        btatualizarAtuProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btatualizarAtuProdMouseClicked(evt);
            }
        });
        jPanelvisProduto.add(btatualizarAtuProd);
        btatualizarAtuProd.setBounds(890, 510, 100, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Visualizar Produto.png"))); // NOI18N
        jPanelvisProduto.add(jLabel5);
        jLabel5.setBounds(0, 0, 1024, 576);

        jPanel1.add(jPanelvisProduto, "visProduto");

        jPanelatuFuncionario.setMaximumSize(new java.awt.Dimension(1024, 576));
        jPanelatuFuncionario.setMinimumSize(new java.awt.Dimension(1024, 576));
        jPanelatuFuncionario.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanelatuFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelatuFuncionarioMouseClicked(evt);
            }
        });
        jPanelatuFuncionario.setLayout(null);

        btcadFuncAtuFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadFuncAtuFuncMouseClicked(evt);
            }
        });
        jPanelatuFuncionario.add(btcadFuncAtuFunc);
        btcadFuncAtuFunc.setBounds(14, 154, 430, 60);
        jPanelatuFuncionario.add(btvisFuncAtuFunc);
        btvisFuncAtuFunc.setBounds(20, 250, 420, 60);

        btcadProdAtuFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadProdAtuFuncMouseClicked(evt);
            }
        });
        jPanelatuFuncionario.add(btcadProdAtuFunc);
        btcadProdAtuFunc.setBounds(20, 354, 420, 60);

        btvisProdAtuFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisProdAtuFuncMouseClicked(evt);
            }
        });
        jPanelatuFuncionario.add(btvisProdAtuFunc);
        btvisProdAtuFunc.setBounds(20, 454, 420, 60);

        nomeCompletoAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        nomeCompletoAtuFunc.setBorder(null);
        jPanelatuFuncionario.add(nomeCompletoAtuFunc);
        nomeCompletoAtuFunc.setBounds(520, 136, 330, 14);

        carteiraDeTrabAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        carteiraDeTrabAtuFunc.setBorder(null);
        jPanelatuFuncionario.add(carteiraDeTrabAtuFunc);
        carteiraDeTrabAtuFunc.setBounds(520, 276, 180, 14);

        tituloDeEleitorAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        tituloDeEleitorAtuFunc.setBorder(null);
        jPanelatuFuncionario.add(tituloDeEleitorAtuFunc);
        tituloDeEleitorAtuFunc.setBounds(790, 230, 180, 14);

        pisAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        pisAtuFunc.setBorder(null);
        jPanelatuFuncionario.add(pisAtuFunc);
        pisAtuFunc.setBounds(790, 276, 180, 14);

        cepAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        cepAtuFunc.setBorder(null);
        jPanelatuFuncionario.add(cepAtuFunc);
        cepAtuFunc.setBounds(510, 370, 190, 14);

        numeroAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        numeroAtuFunc.setToolTipText("");
        numeroAtuFunc.setBorder(null);
        numeroAtuFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroAtuFuncActionPerformed(evt);
            }
        });
        jPanelatuFuncionario.add(numeroAtuFunc);
        numeroAtuFunc.setBounds(510, 420, 190, 14);

        cidadeAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        cidadeAtuFunc.setBorder(null);
        jPanelatuFuncionario.add(cidadeAtuFunc);
        cidadeAtuFunc.setBounds(510, 470, 190, 14);

        logradouroAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        logradouroAtuFunc.setBorder(null);
        jPanelatuFuncionario.add(logradouroAtuFunc);
        logradouroAtuFunc.setBounds(790, 370, 180, 14);

        complementoAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        complementoAtuFunc.setBorder(null);
        jPanelatuFuncionario.add(complementoAtuFunc);
        complementoAtuFunc.setBounds(790, 420, 180, 14);

        bairroAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        bairroAtuFunc.setBorder(null);
        jPanelatuFuncionario.add(bairroAtuFunc);
        bairroAtuFunc.setBounds(790, 470, 180, 14);

        jComboBox1.setBackground(new java.awt.Color(255, 60, 60));
        jComboBox1.setForeground(new java.awt.Color(255, 60, 60));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelatuFuncionario.add(jComboBox1);
        jComboBox1.setBounds(510, 510, 190, 30);

        jComboBox2.setBackground(new java.awt.Color(255, 60, 60));
        jComboBox2.setForeground(new java.awt.Color(255, 60, 60));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelatuFuncionario.add(jComboBox2);
        jComboBox2.setBounds(860, 130, 120, 30);

        btcancelarAtuFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcancelarAtuFuncMouseClicked(evt);
            }
        });
        jPanelatuFuncionario.add(btcancelarAtuFunc);
        btcancelarAtuFunc.setBounds(770, 510, 100, 50);

        rgAtuFunc.setBackground(new java.awt.Color(255, 232, 232));
        rgAtuFunc.setBorder(null);
        try {
            rgAtuFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelatuFuncionario.add(rgAtuFunc);
        rgAtuFunc.setBounds(520, 180, 170, 20);

        jFormattedTextField1.setBackground(new java.awt.Color(255, 232, 232));
        jFormattedTextField1.setBorder(null);
        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(45, 10));
        jPanelatuFuncionario.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(790, 180, 170, 20);

        jFormattedTextField2.setBackground(new java.awt.Color(255, 232, 232));
        jFormattedTextField2.setBorder(null);
        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelatuFuncionario.add(jFormattedTextField2);
        jFormattedTextField2.setBounds(520, 230, 180, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Atualizar Funcionário3.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanelatuFuncionario.add(jLabel6);
        jLabel6.setBounds(0, -20, 1020, 610);

        jPanel1.add(jPanelatuFuncionario, "atuFuncionario");

        jPanelatuProduto.setMaximumSize(new java.awt.Dimension(1024, 576));
        jPanelatuProduto.setMinimumSize(new java.awt.Dimension(1024, 576));
        jPanelatuProduto.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanelatuProduto.setLayout(null);

        btcadFuncAtuProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadFuncAtuProdMouseClicked(evt);
            }
        });
        jPanelatuProduto.add(btcadFuncAtuProd);
        btcadFuncAtuProd.setBounds(14, 154, 430, 60);

        btvisFuncAtuProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisFuncAtuProdMouseClicked(evt);
            }
        });
        jPanelatuProduto.add(btvisFuncAtuProd);
        btvisFuncAtuProd.setBounds(14, 254, 430, 60);

        btvisProdAtuProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btvisProdAtuProdMouseClicked(evt);
            }
        });
        jPanelatuProduto.add(btvisProdAtuProd);
        btvisProdAtuProd.setBounds(20, 450, 420, 70);

        btcadProdAtuProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcadProdAtuProdMouseClicked(evt);
            }
        });
        jPanelatuProduto.add(btcadProdAtuProd);
        btcadProdAtuProd.setBounds(20, 350, 420, 70);

        nomeProdAtuProd.setBackground(new java.awt.Color(255, 232, 232));
        nomeProdAtuProd.setBorder(null);
        jPanelatuProduto.add(nomeProdAtuProd);
        nomeProdAtuProd.setBounds(520, 140, 450, 14);

        quantidadeAtuProd.setBackground(new java.awt.Color(255, 232, 232));
        quantidadeAtuProd.setBorder(null);
        jPanelatuProduto.add(quantidadeAtuProd);
        quantidadeAtuProd.setBounds(520, 200, 180, 14);

        precoAtuProd.setBackground(new java.awt.Color(255, 232, 232));
        precoAtuProd.setBorder(null);
        jPanelatuProduto.add(precoAtuProd);
        precoAtuProd.setBounds(790, 200, 180, 14);

        descricaoAtuProd.setBackground(new java.awt.Color(255, 232, 232));
        descricaoAtuProd.setBorder(null);

        jTextArea2.setBackground(new java.awt.Color(255, 232, 232));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(null);
        descricaoAtuProd.setViewportView(jTextArea2);

        jPanelatuProduto.add(descricaoAtuProd);
        descricaoAtuProd.setBounds(520, 270, 450, 150);

        btcancelarAtuProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcancelarAtuProdMouseClicked(evt);
            }
        });
        jPanelatuProduto.add(btcancelarAtuProd);
        btcancelarAtuProd.setBounds(770, 510, 110, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Atualizar Produto 3.png"))); // NOI18N
        jPanelatuProduto.add(jLabel7);
        jLabel7.setBounds(0, 0, 1024, 576);

        jPanel1.add(jPanelatuProduto, "atuProduto");

        getContentPane().add(jPanel1, "card2");

        jMenu1.setText("Início");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Início");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cadastrar Funcionário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Visualizar Funcionário");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Cadastrar Produto");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Visualizar Produto");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "Inicio");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadFuncionario");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visFuncionario");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "Inicio");
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadProduto");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visProduto");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btcadFuncIniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadFuncIniMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadFuncionario");
    }//GEN-LAST:event_btcadFuncIniMouseClicked

    private void btvisFuncIniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisFuncIniMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visFuncionario");
    }//GEN-LAST:event_btvisFuncIniMouseClicked

    private void btcadProdIniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadProdIniMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadProduto");
    }//GEN-LAST:event_btcadProdIniMouseClicked

    private void btvisProdIniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisProdIniMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visProduto");
    }//GEN-LAST:event_btvisProdIniMouseClicked

    private void btcadFuncCadFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadFuncCadFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadFuncionario");
    }//GEN-LAST:event_btcadFuncCadFuncMouseClicked

    private void btvisFuncCadFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisFuncCadFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visFuncionario");
    }//GEN-LAST:event_btvisFuncCadFuncMouseClicked

    private void btcadProdCadFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadProdCadFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadProduto");
    }//GEN-LAST:event_btcadProdCadFuncMouseClicked

    private void btvisProdCadFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisProdCadFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visProduto");
    }//GEN-LAST:event_btvisProdCadFuncMouseClicked

    private void estadoCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCadFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoCadFuncActionPerformed

    private void btcadFuncVisFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadFuncVisFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadFuncionario");
    }//GEN-LAST:event_btcadFuncVisFuncMouseClicked

    private void btcadProdVisFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadProdVisFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadProduto");
    }//GEN-LAST:event_btcadProdVisFuncMouseClicked

    private void btvisProdVisFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisProdVisFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visProduto");
    }//GEN-LAST:event_btvisProdVisFuncMouseClicked

    private void nomeCompletoCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCompletoCadFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCompletoCadFuncActionPerformed

    private void btcancelarCadFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcancelarCadFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "Inicio");
    }//GEN-LAST:event_btcancelarCadFuncMouseClicked

    private void btcadFuncCadProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadFuncCadProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadFuncionario");
    }//GEN-LAST:event_btcadFuncCadProdMouseClicked

    private void btvisFuncCadProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisFuncCadProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visFuncionario");
    }//GEN-LAST:event_btvisFuncCadProdMouseClicked

    private void btvisProdCadProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisProdCadProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visProduto");
    }//GEN-LAST:event_btvisProdCadProdMouseClicked

    private void btcancelarCadProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcancelarCadProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "Inicio");
    }//GEN-LAST:event_btcancelarCadProdMouseClicked

    private void btcadFuncVisProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadFuncVisProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadFuncionario");
    }//GEN-LAST:event_btcadFuncVisProdMouseClicked

    private void btvisFuncVisProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisFuncVisProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visFuncionario");
    }//GEN-LAST:event_btvisFuncVisProdMouseClicked

    private void btcadProdVisProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadProdVisProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadProduto");
    }//GEN-LAST:event_btcadProdVisProdMouseClicked

    private void btatualizarVisFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btatualizarVisFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "atuFuncionario");
    }//GEN-LAST:event_btatualizarVisFuncMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btcadFuncAtuFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadFuncAtuFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadFuncionario");
    }//GEN-LAST:event_btcadFuncAtuFuncMouseClicked

    private void jPanelatuFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelatuFuncionarioMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visFuncionario");
    }//GEN-LAST:event_jPanelatuFuncionarioMouseClicked

    private void btcadProdAtuFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadProdAtuFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadProduto");
    }//GEN-LAST:event_btcadProdAtuFuncMouseClicked

    private void btvisProdAtuFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisProdAtuFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visProduto");
    }//GEN-LAST:event_btvisProdAtuFuncMouseClicked

    private void numeroAtuFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroAtuFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroAtuFuncActionPerformed

    private void btcancelarAtuFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcancelarAtuFuncMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visFuncionario");
    }//GEN-LAST:event_btcancelarAtuFuncMouseClicked

    private void btcadProdAtuProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadProdAtuProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadProduto");
    }//GEN-LAST:event_btcadProdAtuProdMouseClicked

    private void btcadFuncAtuProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcadFuncAtuProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "cadFuncionario");
    }//GEN-LAST:event_btcadFuncAtuProdMouseClicked

    private void btvisProdAtuProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisProdAtuProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visProduto");
    }//GEN-LAST:event_btvisProdAtuProdMouseClicked

    private void btvisFuncAtuProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btvisFuncAtuProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "visFuncionario");
    }//GEN-LAST:event_btvisFuncAtuProdMouseClicked

    private void rgCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgCadFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgCadFuncActionPerformed

    private void cpfCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfCadFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfCadFuncActionPerformed

    private void btatualizarAtuProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btatualizarAtuProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "atuProduto");
    }//GEN-LAST:event_btatualizarAtuProdMouseClicked

    private void btcancelarAtuProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcancelarAtuProdMouseClicked
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "Inicio");
    }//GEN-LAST:event_btcancelarAtuProdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrame desk = new Desktop();
            desk.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TituloDeEleitorCadFunc;
    private javax.swing.JTextField bairroAtuFunc;
    private javax.swing.JTextField bairroCadFunc;
    private javax.swing.JLabel btatualizarAtuProd;
    private javax.swing.JLabel btatualizarVisFunc;
    private javax.swing.JLabel btcadFuncAtuFunc;
    private javax.swing.JLabel btcadFuncAtuProd;
    private javax.swing.JLabel btcadFuncCadFunc;
    private javax.swing.JLabel btcadFuncCadProd;
    private javax.swing.JLabel btcadFuncIni;
    private javax.swing.JLabel btcadFuncVisFunc;
    private javax.swing.JLabel btcadFuncVisProd;
    private javax.swing.JLabel btcadProdAtuFunc;
    private javax.swing.JLabel btcadProdAtuProd;
    private javax.swing.JLabel btcadProdCadFunc;
    private javax.swing.JLabel btcadProdIni;
    private javax.swing.JLabel btcadProdVisFunc;
    private javax.swing.JLabel btcadProdVisProd;
    private javax.swing.JLabel btcadastrarCadFunc;
    private javax.swing.JLabel btcancelarAtuFunc;
    private javax.swing.JLabel btcancelarAtuProd;
    private javax.swing.JLabel btcancelarCadFunc;
    private javax.swing.JLabel btcancelarCadProd;
    private javax.swing.JLabel btvisFuncAtuFunc;
    private javax.swing.JLabel btvisFuncAtuProd;
    private javax.swing.JLabel btvisFuncCadFunc;
    private javax.swing.JLabel btvisFuncCadProd;
    private javax.swing.JLabel btvisFuncIni;
    private javax.swing.JLabel btvisFuncVisProd;
    private javax.swing.JLabel btvisProdAtuFunc;
    private javax.swing.JLabel btvisProdAtuProd;
    private javax.swing.JLabel btvisProdCadFunc;
    private javax.swing.JLabel btvisProdCadProd;
    private javax.swing.JLabel btvisProdIni;
    private javax.swing.JLabel btvisProdVisFunc;
    private javax.swing.JComboBox<String> cargoCadFunc;
    private javax.swing.JTextField carteiraDeTrabAtuFunc;
    private javax.swing.JTextField carteiraDeTrabCadFunc;
    private javax.swing.JTextField cepAtuFunc;
    private javax.swing.JTextField cepCadFunc;
    private javax.swing.JTextField cidadeAtuFunc;
    private javax.swing.JTextField cidadeCadFunc;
    private javax.swing.JTextField complementoAtuFunc;
    private javax.swing.JTextField complementoCadFunc;
    private javax.swing.JFormattedTextField cpfCadFunc;
    private javax.swing.JFormattedTextField dataNascCadFunc;
    private javax.swing.JScrollPane descricaoAtuProd;
    private javax.swing.JScrollPane descricaoCadProd;
    private javax.swing.JComboBox<String> estadoCadFunc;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelatuFuncionario;
    private javax.swing.JPanel jPanelatuProduto;
    private javax.swing.JPanel jPanelcadFuncionario;
    private javax.swing.JPanel jPanelcadProduto;
    private javax.swing.JPanel jPanelvisFuncionario;
    private javax.swing.JPanel jPanelvisProduto;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField logradouroAtuFunc;
    private javax.swing.JTextField logradouroCadFunc;
    private javax.swing.JTextField nomeCompletoAtuFunc;
    private javax.swing.JTextField nomeCompletoCadFunc;
    private javax.swing.JTextField nomeProdAtuProd;
    private javax.swing.JTextField nomeProdutoCadProd;
    private javax.swing.JTextField numeroAtuFunc;
    private javax.swing.JTextField numeroCadFunc;
    private javax.swing.JTextField pisAtuFunc;
    private javax.swing.JTextField pisCadFunc;
    private javax.swing.JTextField precoAtuProd;
    private javax.swing.JTextField precoCadProd;
    private javax.swing.JTextField quantidadeAtuProd;
    private javax.swing.JTextField qunatidadeCadProd;
    private javax.swing.JFormattedTextField rgAtuFunc;
    private javax.swing.JFormattedTextField rgCadFunc;
    private javax.swing.JTextField tituloDeEleitorAtuFunc;
    // End of variables declaration//GEN-END:variables
}
