/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manage5;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author leonardo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        try {
            iniFont();
        } catch (FontFormatException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        user_image.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campo1 = new javax.swing.JPanel();
        user_image = new javax.swing.JLabel();
        user_text = new javax.swing.JTextField();
        type1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campo1.setBackground(new java.awt.Color(0, 177, 255));
        campo1.setPreferredSize(new java.awt.Dimension(1900, 1000));
        campo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manage5/image/user.png"))); // NOI18N
        campo1.add(user_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 275, -1, -1));

        user_text.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        user_text.setText("USER");
        user_text.setBorder(null);
        user_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_textMouseClicked(evt);
            }
        });
        user_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_textActionPerformed(evt);
            }
        });
        campo1.add(user_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 1060, 50));

        type1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        type1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manage5/image/Retângulo 1.png"))); // NOI18N
        type1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campo1.add(type1, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 461, -1, -1));

        getContentPane().add(campo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void user_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_textActionPerformed

    private void user_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_textMouseClicked
        user_text.setText("");
        user_text.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_user_textMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    public void iniFont() throws FontFormatException{
        Font minhaFonte;
        try {
            minhaFonte = Font.createFont(Font.TRUETYPE_FONT, new File("C:\\Users\\leonardo\\Documents\\NetBeansProjects\\manage5.1.0\\font\\RobotoMono-Thin.ttf")).deriveFont(Font.PLAIN, 28);
            user_text.setFont(minhaFonte);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel campo1;
    private javax.swing.JLabel type1;
    private javax.swing.JLabel user_image;
    private javax.swing.JTextField user_text;
    // End of variables declaration//GEN-END:variables
}
